# Your Solution
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      imagePullSecrets:
      - name: acr-auth  # Place the imagePullSecrets here
      containers: 
      - name: book-catalog
        image: varshsit722week7.azurecr.io/varsh_book_catalog:1  # Ensure this is correct
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://sit722_part_3_6c9v_user:PIt83yDKEGX6IaNxbzIqersdKrIwmcCy@dpg-crm1t4o8fa8c73a05sh0-a.oregon-postgres.render.com/sit722_part_3_6c9v"

---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      #nodePort: 30001  # Ensure this is unique

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      imagePullSecrets:
      - name: acr-auth  # Place the imagePullSecrets here
      containers: 
      - name: inventory-management
        image: varshsit722week7.azurecr.io/varsh_inventory-management:1  # Ensure this is correct
        ports:
        - containerPort: 8001
        env:
        - name: DATABASE_URL
          value: "postgresql://sit722_part_3_6c9v_user:PIt83yDKEGX6IaNxbzIqersdKrIwmcCy@dpg-crm1t4o8fa8c73a05sh0-a.oregon-postgres.render.com/sit722_part_3_6c9v"

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
     # nodePort: 30002  # Ensure this is unique
